AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - bin/**/*
    - spec/spec_helper.rb
    - ./*.gemspec

Style/StringLiterals:
  EnforcedStyle: double_quotes

Naming/FileName:
  Exclude:
    - "lib/atomic-sidekiq.rb"

Style/DoubleNegation:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/LineLength:
  Exclude:
    - spec/**/*.rb
