language: ruby
sudo: false
cache: bundler
services:
  - redis-server
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
before_script:
  # include ChromeDriver in PATH
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
  # start Chrome and listen on localhost
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &
before_install:
  - gem install bundler
  - gem update bundler
rvm:
  - 2.2.2
  - 2.3.5
  - 2.4.2
  - 2.5.0
script:
  - bundle exec rubocop
  - bundle exec rspec
