version: '2'

services:
  base:
    build: .
    env_file:
      - docker.env
    volumes:
      - .:/sidekiq-atomic
    image: sidekiq-atomic

  test:
    extends:
      service: base
    command: bin/test
    depends_on:
      - redis
    ports:
      - 3000:3000
    volumes_from:
      - bundle

  redis:
    image: redis:3.2-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/data

  bundle:
    image: tianon/true
    volumes:
      - bundle:/bundle

volumes:
  redis:
  bundle:
